chore(builder): Split artifact builder in multiple parts
bonitasoft/bonita-ui-designer-artifact-builder pull request #21
Opened 2023-08-14 14:09 UTC by benjaminParisel

* Create common, model and generator package
* Move test
* Bump from junit4 to junit5

2023-08-15 12:23 UTC, rbioteau reviewed
I'm not found of the `IHtmlBuilder` convention.
Just make `HtmlBuilder` the interface name and `HtmlBuilderImpl` or `DefaultHtmlBuilder` or   `DefaultHtmlBuilderImpl` the concrete implementation class name.

This convention seems broadly adopted.
Some [reference](https://thomaspoignant.medium.com/java-how-to-name-interface-and-implementor-94c0fa564b87)

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/pom.xml
> +      <version>${project.version}</version>
Add this dependency in the BOM

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/pom.xml
> +      <version>${project.version}</version>
Same as above

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/pom.xml
> +      <version>${project.version}</version>
Same as above

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/pom.xml
> +      <version>${project.version}</version>
not needed

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/pom.xml
> +      <version>5.3.1</version>
use a maven properties

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/pom.xml
> +      <version>5.3.1</version>
use a maven property

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/src/main/java/org/bonitasoft/web/designer/DefaultArtifactBuilder.java
> +    public String buildHtml(Page page, String context) throws RuntimeException {
Create `BuildHtmlException` instead of using directly a `RuntimeException`

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/src/main/java/org/bonitasoft/web/designer/DefaultArtifactBuilder.java
> +    public String buildHtml(Fragment fragment, String context) throws RuntimeException {
Same as above

2023-08-15 12:23 UTC, rbioteau commented on artifact-builder/src/main/java/org/bonitasoft/web/designer/controller/export/WidgetExporter.java
> +import org.bonitasoft.web.designer.model.widgets.Widget;
Plural form is discouraged in package names

2023-08-18 15:37 UTC, rbioteau requested changes

2023-08-21 09:15 UTC, benjaminParisel commented on model/pom.xml
> +    <dependency>
I already do it, i just miss to remove the dependency in pom :ok_hand:

2023-08-21 12:02 UTC, rbioteau commented on generator-angularjs/src/test/java/org/bonitasoft/web/angularjs/rendering/DefaultHtmlGeneratorTest.java
> +    //    @Test
Commented tests ?

2023-08-21 15:05 UTC, rbioteau approved these changes

2023-08-21 15:05 UTC, merged